export default function FavIcons() {
  return (
    <>
      <link rel="icon" href="/favicon.svg" />
      <link
        rel="mask-icon"
        href="/favicon.svg"
        type="image/svg+xml"
        color="#000000"
      />
      {/* Below generated by real-favicon */}
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/favicon-16x16.png"
      />
      <link rel="manifest" href="/site.webmanifest" />
      <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#777777" />
      <meta name="apple-mobile-web-app-title" content="Geekality" />
      <meta name="application-name" content="Geekality" />
      <meta name="msapplication-TileColor" content="#ffffff" />
      <meta name="theme-color" content="#ffffff" />
    </>
  )
}
