import '@/styles/globals.css'

import { type ReactNode } from 'react'
import { type Metadata } from 'next'

import { BASE_URL, absolute } from '@/config/url'
import { site } from '@/config'
import feed from '@/content/feed'

import Link from '@/components/Link'
import MenuItems from './MenuItems'
import Favicon from './Favicon'
import { Analytics } from '@vercel/analytics/react'

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    absolute: site.title,
    template: '%s | ' + site.title,
  },
  description: 'My website',
  alternates: {
    types: {
      'application/rss+xml': [
        { url: absolute('blog/feed/xml'), title: feed.title },
      ],
      'application/atom+xml': [
        { url: absolute('blog/feed/atom'), title: feed.title },
      ],
      'application/json': [
        { url: absolute('blog/feed/json'), title: feed.title },
      ],
    },
  },
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" />
        <link
          rel="mask-icon"
          href="/favicon.svg"
          type="image/svg+xml"
          color="#000000"
        />
        {/* Below generated by real-favicon */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#777777" />
        <meta name="apple-mobile-web-app-title" content="Geekality" />
        <meta name="application-name" content="Geekality" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="m-0 overflow-y-scroll antialiased text-gray-900 dark:text-gray-100 bg-gray-100 dark:bg-gray-900 flex flex-col min-h-[100dvh]">
        <header className="sticky top-0 z-10 border-b-2 border-gray-800 select-none bg-gray-300/70 backdrop-blur-sm text-gray-950 dark:text-gray-50 dark:bg-gray-700/70 dark:border-gray-200 sm:text-2xl">
          <div className="container flex text-lg">
            <div className="mr-auto">
              <Link
                href="/"
                rel="home"
                className="block px-4 py-3 hover:bg-gray-400 dark:hover:bg-gray-600"
              >
                {site.title}
              </Link>
            </div>
            <nav aria-label="Main navigation">
              <ul className="flex">
                <MenuItems />
              </ul>
            </nav>
          </div>
        </header>

        <main className="container flex-grow p-4">{children}</main>

        <footer className="p-2 mt-8 text-xs border-t-2 border-gray-300 select-none dark:border-gray-700">
          <div className="container flex gap-4">
            <div className="py-2">– {site.tagline}</div>
            <div className="flex ml-auto">
              <Link
                href="/about"
                aria-label="About me"
                rel="author"
                className="-translate-y-0.5"
              >
                <Favicon
                  role="img"
                  aria-label="Logo"
                  className="h-8 fill-gray-950 dark:fill-gray-50"
                />
              </Link>
            </div>
          </div>
        </footer>

        <Analytics />
      </body>
    </html>
  )
}
